# Exercícios

### Bibliotecas

In [9]:
# Libs
import numpy as np
import pandas as pd

#### Exercício

Gere uma matriz 4x4 de números igualmente espaçados entre 5 e 11 e calcule o total de memória utilizado para armazenar este array

In [10]:
matriz = np.linspace(5, 11, 16).reshape(4, 4)
total_memoria = matriz.nbytes
total_memoria_mb = total_memoria / 1024 / 1024
print(f"Total de memória utilizado: {total_memoria} bytes")
print(f"Total de memória utilizado: {total_memoria_mb} MB")

Total de memória utilizado: 128 bytes
Total de memória utilizado: 0.0001220703125 MB


#### Exercício

Assumindo que você tenha um array de apenas inteiros, crie uma função que converte-o para o tipo de dado que minimiza seu uso de memória

In [11]:
def minimiza_memoria(array: np.ndarray) -> np.ndarray:
    """
    Minimiza o uso de memório de um determinado array
    de inteiros
    
    :param array: array a ser minimizado
    :return: array com o tipo ajustado
    """
    return np.array(array, dtype=np.int8)


arr = [1, 2, 3, 4, 5]
result = minimiza_memoria(arr)

print(f"Resultado {result}, Total de memória utilizado pelo resultado: {result.nbytes} bytes")

Resultado [1 2 3 4 5], Total de memória utilizado pelo resultado: 5 bytes


#### Exercício

Dado um vetor unidimensional de valores converta-o para uma matriz bi-dimensional com base em um valor de passo e um valor de janela, de tal forma que cada linha dessa matriz contenha o número de colunas definido na janela e que nós percorremos, a cada iteração, o número de passo em termos de elemento.

Por exemplo:  

        Entrada >  
        array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]  
        Passo = 2  
        Janela = 4  

Geraria uma saída de:  

    Saída > [[ 0  1  2  3]  
             [ 2  3  4  5]  
             [ 4  5  6  7]  
             [ 6  7  8  9]  
             [ 8  9 10 11]  
             [10 11 12 13]  
             [12 13 14 15]  
             [14 15 16 17]]  

Veja que cada linha contém 4 colunas = janelas. A primeira linha é formada por 0-3, ou seja, os 4 primeiros elementos do array, enquanto que a segunda linha é de 2-5, de forma que ela pula os 2 primeiros elementos (passo) e percorre mais 4 elementos (janela) do array

In [12]:
def gera_matriz(array, passo=5, janela=5):
    n_iter = ((array.size - janela) // passo) + 1
    return np.array(
        [
            array[s:(s + janela)] 
            for s in np.arange(0, n_iter * passo, passo)
        ]
    )

In [13]:
# Testando a função
array = np.arange(19)
passo = 2  
janela = 4
gera_matriz(array, passo, janela)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13],
       [12, 13, 14, 15],
       [14, 15, 16, 17]])

#### Exercício

Crie uma função que permita criar uma matriz quadrada com os seguintes formatos:

Q -> 1 1 1 1
     1 0 0 1
     1 0 0 1
     1 1 1 1
V -> 1 0 0 1
     1 0 0 1
     1 0 0 1
     1 0 0 1
H -> 1 1 1 1
     0 0 0 0
     0 0 0 0
     1 1 1 1
P -> 0 0 0 0
     0 1 1 0
     0 1 1 0
     0 0 0 0

In [14]:
def criar_matriz_quadrada(formato, tamanho):
    matriz = []
    for i in range(tamanho):
        linha = []
        for j in range(tamanho):
            if formato == 'Q':
                if i == 0 or i == tamanho-1 or j == 0 or j == tamanho-1:
                    linha.append(1)
                else:
                    linha.append(0)
            elif formato == 'V':
                if j == 0 or j == tamanho-1:
                    linha.append(1)
                else:
                    linha.append(0)
            elif formato == 'H':
                if i == 0 or i == tamanho-1:
                    linha.append(1)
                else:
                    linha.append(0)
            elif formato == 'P':
                if i == tamanho//2-1 or i == tamanho//2:
                    if j == tamanho//2-1 or j == tamanho//2:
                        linha.append(1)
                    else:
                        linha.append(0)
                else:
                    linha.append(0)
        matriz.append(linha)
    return matriz


In [15]:
matriz_q = criar_matriz_quadrada('Q', 5)
matriz_v = criar_matriz_quadrada('V', 5)
matriz_h = criar_matriz_quadrada('H', 5)
matriz_p = criar_matriz_quadrada('P', 5)
matriz_q, matriz_v,matriz_h, matriz_p

([[1, 1, 1, 1, 1],
  [1, 0, 0, 0, 1],
  [1, 0, 0, 0, 1],
  [1, 0, 0, 0, 1],
  [1, 1, 1, 1, 1]],
 [[1, 0, 0, 0, 1],
  [1, 0, 0, 0, 1],
  [1, 0, 0, 0, 1],
  [1, 0, 0, 0, 1],
  [1, 0, 0, 0, 1]],
 [[1, 1, 1, 1, 1],
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0],
  [1, 1, 1, 1, 1]],
 [[0, 0, 0, 0, 0],
  [0, 1, 1, 0, 0],
  [0, 1, 1, 0, 0],
  [0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0]])