# Numpy
OBJETIVO: O objetivo deste notebook é explicar como a biblioteca numpy funciona e as principais operações com arrays

### Bibliotecas

In [1]:
# Libs
import os
import numpy as np
import pandas as pd
from pathlib import Path

%config Completer.use_jedi = False

### Criando Array e Matriz

In [2]:
# Array
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
# Matriz
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Dados isso é fácil perceber que um array tem as seguintes características que podem ser acessadas na forma de atributos deste objeto:

- dtype: O tipo de dados do array
- shape: O tamanho do array em linhas e colunas
- size: O tamanho do array em quantidade de elementos
- itemsize: O consumo de memória de cada elemento do array (em bytes)
- strides: Uma distancia em bytes entre os elementos armazenados na memória

In [4]:
# Informações 
print(
    f"array: dtype={array.dtype} | shape={array.shape}| size={array.size} "
    f"| itemsize={array.itemsize} | strides={array.strides}"
)

print(
    f"matriz: dtype={matriz.dtype} | shape={matriz.shape} | size={matriz.size} "
    f"| itemsize={matriz.itemsize} | strides={matriz.strides}"
)

array: dtype=int32 | shape=(5,)| size=5 | itemsize=4 | strides=(4,)
matriz: dtype=int32 | shape=(2, 3) | size=6 | itemsize=4 | strides=(12, 4)


In [5]:
# np.zeros -> Cria um array preenchido com zeros
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
# np.ones -> Cria um array preenchido com um's
np.ones(shape=(3, ))

array([1., 1., 1.])

In [7]:
# np.eye -> Cria a matriz identidade com o tamanho especificado
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# np.arange -> Mesma coisa que a função range, só que para arrays
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
# np.linspace -> Cria um array entre dois números espaçados linearmente
np.linspace(5, 10, num=5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [10]:
# np.logspace -> Cria um array entre dois números espaçados logaritimicamente
np.logspace(0, 1, 3)

array([ 1.        ,  3.16227766, 10.        ])

In [11]:
# np.random.int -> Cria um array de valores aleatórios entre um valor menor e maior (exclusivo)
np.random.randint(0, 10, size=(5, 5))

array([[8, 2, 7, 4, 0],
       [9, 1, 1, 9, 9],
       [9, 9, 1, 4, 1],
       [7, 6, 4, 6, 0],
       [0, 0, 5, 4, 5]])

In [12]:
# np.random.normal -> Cria um array aleatório com valores baseados em uma distribuição normal
np.random.normal(1, 2, 10)

array([ 2.55949452, -1.31214031,  2.84840448,  0.47423768, -0.29185024,
        3.58052072,  0.94087285,  0.62945802,  1.87251855, -0.78059559])

É interessante notar que algumas dessas funções não permitem passar o tamanho do array (como np.arange), por isso muitas vezes é comum combina-las com o método reshape

In [13]:
# Usando reshape
a = np.arange(12)
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Tipagem
Uma das diferenças mais gritantes entre arrays e listas é sua tipagem. Enquanto listas podem conter múltiplos tipos de dados (inteiros, strings, floats, etc) arrays tendem a possuir tipagem fixa e tal tipagem pode ser modificada utilizando o método astype

In [14]:
arr = np.array([1, 2, 3])
print(arr.dtype, arr)

int32 [1 2 3]


In [15]:
arr = np.array([1, 2, 3])
arr = arr.astype("float")
print(arr.dtype, arr)

float64 [1. 2. 3.]


In [16]:
arr = np.array([1, 2, 3], dtype=np.uint8)
print(arr.dtype, arr)

uint8 [1 2 3]


In [17]:
arr = np.array(["ola", 2.1, [2, 3, 4]], dtype="object")
arr

array(['ola', 2.1, list([2, 3, 4])], dtype=object)

In [18]:
arr.shape

(3,)