# Numpy
OBJETIVO: O objetivo deste notebook é explicar como a biblioteca numpy funciona e as principais operações com arrays

### Bibliotecas

In [1]:
# Libs
import os
import numpy as np
import pandas as pd
from pathlib import Path

%config Completer.use_jedi = False

### Criando Array e Matriz

In [2]:
# Array
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [3]:
# Matriz
matriz = np.array([[1, 2, 3], [4, 5, 6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

Dados isso é fácil perceber que um array tem as seguintes características que podem ser acessadas na forma de atributos deste objeto:

- dtype: O tipo de dados do array
- shape: O tamanho do array em linhas e colunas
- size: O tamanho do array em quantidade de elementos
- itemsize: O consumo de memória de cada elemento do array (em bytes)
- strides: Uma distancia em bytes entre os elementos armazenados na memória

In [4]:
# Informações 
print(
    f"array: dtype={array.dtype} | shape={array.shape}| size={array.size} "
    f"| itemsize={array.itemsize} | strides={array.strides}"
)

print(
    f"matriz: dtype={matriz.dtype} | shape={matriz.shape} | size={matriz.size} "
    f"| itemsize={matriz.itemsize} | strides={matriz.strides}"
)

array: dtype=int32 | shape=(5,)| size=5 | itemsize=4 | strides=(4,)
matriz: dtype=int32 | shape=(2, 3) | size=6 | itemsize=4 | strides=(12, 4)


In [5]:
# np.zeros -> Cria um array preenchido com zeros
np.zeros(shape=(3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
# np.ones -> Cria um array preenchido com um's
np.ones(shape=(3, ))

array([1., 1., 1.])

In [7]:
# np.eye -> Cria a matriz identidade com o tamanho especificado
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
# np.arange -> Mesma coisa que a função range, só que para arrays
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [9]:
# np.linspace -> Cria um array entre dois números espaçados linearmente
np.linspace(5, 10, num=5)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [10]:
# np.logspace -> Cria um array entre dois números espaçados logaritimicamente
np.logspace(0, 1, 3)

array([ 1.        ,  3.16227766, 10.        ])

In [11]:
# np.random.int -> Cria um array de valores aleatórios entre um valor menor e maior (exclusivo)
np.random.randint(0, 10, size=(5, 5))

array([[6, 4, 8, 9, 9],
       [0, 6, 0, 0, 1],
       [0, 6, 6, 5, 0],
       [2, 9, 2, 7, 8],
       [4, 1, 6, 6, 5]])

In [12]:
# np.random.normal -> Cria um array aleatório com valores baseados em uma distribuição normal
np.random.normal(1, 2, 10)

array([ 5.8804125 ,  0.74680619,  0.59569771,  1.12855449, -2.11687002,
        3.39313232,  0.52560781,  0.19151474, -0.23981341,  1.97476345])

É interessante notar que algumas dessas funções não permitem passar o tamanho do array (como np.arange), por isso muitas vezes é comum combina-las com o método reshape

In [13]:
# Usando reshape
a = np.arange(12)
a = a.reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Tipagem
Uma das diferenças mais gritantes entre arrays e listas é sua tipagem. Enquanto listas podem conter múltiplos tipos de dados (inteiros, strings, floats, etc) arrays tendem a possuir tipagem fixa e tal tipagem pode ser modificada utilizando o método astype

In [14]:
arr = np.array([1, 2, 3])
print(arr.dtype, arr)

int32 [1 2 3]


In [15]:
arr = np.array([1, 2, 3])
arr = arr.astype("float")
print(arr.dtype, arr)

float64 [1. 2. 3.]


In [16]:
arr = np.array([1, 2, 3], dtype=np.uint8)
print(arr.dtype, arr)

uint8 [1 2 3]


In [17]:
arr = np.array(["ola", 2.1, [2, 3, 4]], dtype="object")
arr

array(['ola', 2.1, list([2, 3, 4])], dtype=object)

In [18]:
arr.shape

(3,)

### Indexação
Tal como listas arrays são objetos indexáveis de maneira similar, de forma que a sintaxe de chaves e os slices funcionam normalmente

In [19]:
array = np.arange(1, 10)
matriz = np.random.normal(1, 2, (3, 3))

array, matriz

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 0.2938554 ,  0.47175225,  2.13044989],
        [ 2.45124063,  5.04428275, -0.74347891],
        [ 4.31997751,  2.83183041,  0.73010298]]))

In [20]:
array[0]

1

In [21]:
matriz[2][-1]

0.7301029806535762

In [22]:
matriz[1]

array([ 2.45124063,  5.04428275, -0.74347891])

In [23]:
array[::-2]

array([9, 7, 5, 3, 1])

Entretanto o numpy oferece uma maneira adicional de indexar elementos selecionando múltiplos indices por meio de uma lista

In [24]:
array[1:3]

array([2, 3])

In [25]:
array[[1, 2]]

array([2, 3])

Por fim, numpy nos oferece a flexibilidade, especialmente com matrizes, de selecionar os elementos de linhas e colunas em conjunto por meio da sintaxe de ",", na qual fornecemos dois slices, o primeiro selecionando linhas e o segundo selecionado colunas

In [26]:
matriz[:, 1]

array([0.47175225, 5.04428275, 2.83183041])

In [27]:
matriz[1, 2]

-0.7434789051617228

In [28]:
matriz[:, [1, 2]]

array([[ 0.47175225,  2.13044989],
       [ 5.04428275, -0.74347891],
       [ 2.83183041,  0.73010298]])

### Mutabilidade
Diferente de listas arrays são objetos imutáveis em tamanho e tipo (como você viu mais acima, para mudar o tipo de array nós criamos um novo)

In [29]:
arr = np.array([1, 2, 3])
# arr.append(4) Vai dar erro
# Entretanto, diferente de tuplas, arrays são mutáveis em conteúdo
arr[2] = 5
arr

array([1, 2, 5])

In [30]:
# Ao tentar mudar o valor de um elemento o numpy o converterá para a tipagem adequada quando possível
arr[1] = 1.7234
arr

array([1, 1, 5])

In [31]:
arr[1] = '3'
arr
# arr[1] = '3.2' tambem vai dar erro
# arr

array([1, 3, 5])

É interessante notar como funciona a alocação de memória para transformações particulares do array que podem afetar sua mutabilidade. Por exemplo, suponhamos que temos os array a, b e c todos criados a partir de transformações do vetor a

In [32]:
a = np.arange(12, dtype='int64')
b = a.reshape(3, 4)
c = a[::2]
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  2  4  6  8 10]


In [33]:
# O que acontece, neste caso, se eu alterar o vetor a?
a[0] = -1
print(a)
print(b)
print(c)

[-1  1  2  3  4  5  6  7  8  9 10 11]
[[-1  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[-1  2  4  6  8 10]


In [34]:
print(f"a: dtype={a.dtype} | shape={a.shape} | size={a.size} | itemsize={a.itemsize} | strides={a.strides}")
print(f"b: dtype={b.dtype} | shape={b.shape} | size={b.size} | itemsize={b.itemsize} | strides={b.strides}")

a: dtype=int64 | shape=(12,) | size=12 | itemsize=8 | strides=(8,)
b: dtype=int64 | shape=(3, 4) | size=12 | itemsize=8 | strides=(32, 8)


In [35]:
print(f"a: dtype={a.dtype} | shape={a.shape} | size={a.size} | itemsize={a.itemsize} | strides={a.strides}")
print(f"c: dtype={c.dtype} | shape={c.shape} | size={c.size} | itemsize={c.itemsize} | strides={c.strides}")

a: dtype=int64 | shape=(12,) | size=12 | itemsize=8 | strides=(8,)
c: dtype=int64 | shape=(6,) | size=6 | itemsize=8 | strides=(16,)


Por fim é importante lembrar que tal como listas e dicionário, arrays são passados como referência em função, de forma que qualquer alteração no array feito dentro de uma função será carregada para fora da mesma

In [36]:
def muda_a(a):
    a[1] = 12890

print(a)
muda_a(a)
print(a)
print(b)
print(c)

[-1  1  2  3  4  5  6  7  8  9 10 11]
[   -1 12890     2     3     4     5     6     7     8     9    10    11]
[[   -1 12890     2     3]
 [    4     5     6     7]
 [    8     9    10    11]]
[-1  2  4  6  8 10]


### Operações
Como descrito anteriormente, numpy é uma biblioteca de algebra linear, de forma que suporta todas as operações vetoriais tradicionais

In [37]:
np.random.seed(42)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
m1 = np.random.randint(1, 10, size=(3, 3))
m2 = np.random.randint(1, 10, size=(3, 3))

print(m1)
print(m2)

[[7 4 8]
 [5 7 3]
 [7 8 5]]
[[4 8 8]
 [3 6 5]
 [2 8 6]]


#### Soma

In [38]:
arr1 + arr2

array([5, 7, 9])

In [39]:
np.add(arr1, arr2)

array([5, 7, 9])

#### Subtração

In [40]:
arr1 - arr2

array([-3, -3, -3])

In [41]:
np.subtract(arr1, arr2)

array([-3, -3, -3])

#### Multiplicação (Escalar)

In [42]:
arr1 * 2

array([2, 4, 6])

In [43]:
arr1 * 2.1

array([2.1, 4.2, 6.3])

In [44]:
np.multiply(arr1 , 2)

array([2, 4, 6])

#### Multiplicação (Element-wise)

In [45]:
arr1 * arr2

array([ 4, 10, 18])

In [46]:
np.multiply(arr1, arr2)

array([ 4, 10, 18])

#### Multiplicação (Produto vetorial)

In [47]:
sum(arr1 * arr2)

32

In [48]:
arr1.dot(arr2)

32

In [49]:
np.dot(arr1, arr2)

32

#### Multiplicação (Cruzada)

In [50]:
np.cross(arr1, arr2)

array([-3,  6, -3])

#### Multiplicação (Matricial)

In [51]:
m1@m2

array([[ 56, 144, 124],
       [ 47, 106,  93],
       [ 62, 144, 126]])

In [52]:
np.matmul(m1, m2)

array([[ 56, 144, 124],
       [ 47, 106,  93],
       [ 62, 144, 126]])

#### Divisão

In [53]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [54]:
np.divide(arr1, arr2)

array([0.25, 0.4 , 0.5 ])

#### Exponenciação

In [55]:
arr1 ** 2

array([1, 4, 9])

In [56]:
arr1 ** arr2

array([  1,  32, 729])

In [57]:
np.power(arr1, arr2)

array([  1,  32, 729])

#### Módulo de um vetor

In [58]:
sum(arr1 * arr1) ** 0.5

3.7416573867739413

In [59]:
np.linalg.norm(arr1)

3.7416573867739413

#### Determinante de uma matriz

In [60]:
np.linalg.det(m1)

-11.00000000000003

#### Matriz inversa

In [61]:
np.linalg.inv(m1)

array([[-1.        , -4.        ,  4.        ],
       [ 0.36363636,  1.90909091, -1.72727273],
       [ 0.81818182,  2.54545455, -2.63636364]])

#### Matriz transposta

In [62]:
np.transpose(m1)

array([[7, 5, 7],
       [4, 7, 8],
       [8, 3, 5]])

In [63]:
m1.T

array([[7, 5, 7],
       [4, 7, 8],
       [8, 3, 5]])

In [64]:
arr1.T

array([1, 2, 3])